//! Build tasks for the utilars crate.
//!
//! - `cargo xtask pull` — fetch the Utila OpenAPI spec into `openapi/utila.v2.json`.
//! - `cargo xtask gen`  — regenerate `src/generated.rs` from the vendored spec.
//!
//! The generated client carries an `Arc<crate::auth::TokenManager>` as its inner state
//! and authenticates every request via the async pre-hook `crate::auth::inject_bearer`.

use std::fs;

use anyhow::{Context, Result};
use progenitor::{GenerationSettings, Generator, InterfaceStyle, TagStyle};
use quote::quote;
use sha2::{Digest, Sha256};

const SPEC_URL: &str = "https://docs.utila.io/openapi/latest_apidocs-v2-readme.openapi.json";
const SPEC_PATH: &str = "openapi/utila.v2.json";
const PROVENANCE_PATH: &str = "openapi/utila.v2.meta.json";
const OUT_PATH: &str = "src/generated.rs";

/// Where the vendored spec came from and which exact revision it is. The spec's `info`
/// only carries a coarse `version` (`v2`) and no date, so `sha256` (of the committed
/// pretty-printed bytes) is the real revision identifier — deterministic, and it changes
/// only when the spec actually changes.
#[derive(serde::Serialize)]
struct Provenance {
    source: String,
    openapi: String,
    title: String,
    version: String,
    sha256: String,
}

/// Derive provenance from the (pretty-printed) spec text.
fn provenance(spec_pretty: &str) -> Result<Provenance> {
    let value: serde_json::Value = serde_json::from_str(spec_pretty)?;
    let sha256 = Sha256::digest(spec_pretty.as_bytes())
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    let field = |path: &[&str]| -> String {
        let mut node = &value;
        for key in path {
            node = &node[key];
        }
        node.as_str().unwrap_or_default().to_string()
    };
    Ok(Provenance {
        source: SPEC_URL.to_string(),
        openapi: field(&["openapi"]),
        title: field(&["info", "title"]),
        version: field(&["info", "version"]),
        sha256,
    })
}

fn main() -> Result<()> {
    match std::env::args().nth(1).as_deref() {
        Some("pull") => pull(),
        Some("gen") => gen(),
        _ => {
            eprintln!("usage: cargo xtask <pull|gen>");
            std::process::exit(2);
        }
    }
}

/// Fetch the spec and write it pretty-printed (so changes show as reviewable diffs), plus a
/// provenance sidecar pinning the exact revision.
fn pull() -> Result<()> {
    eprintln!("fetching {SPEC_URL}");
    let body = ureq::get(SPEC_URL).call()?.into_string()?;
    let value: serde_json::Value = serde_json::from_str(&body)?;
    let pretty = serde_json::to_string_pretty(&value)?;
    fs::create_dir_all("openapi")?;
    fs::write(SPEC_PATH, &pretty)?;
    let prov = provenance(&pretty)?;
    write_provenance(&prov)?;
    eprintln!(
        "wrote {SPEC_PATH} + {PROVENANCE_PATH} (spec {} {}, sha256:{}…)",
        prov.title,
        prov.version,
        short_sha(&prov.sha256),
    );
    Ok(())
}

/// Write the provenance sidecar (kept in sync by both `pull` and `gen`).
fn write_provenance(prov: &Provenance) -> Result<()> {
    fs::write(
        PROVENANCE_PATH,
        format!("{}\n", serde_json::to_string_pretty(prov)?),
    )?;
    Ok(())
}

fn short_sha(sha256: &str) -> String {
    sha256.chars().take(12).collect()
}

/// Generate the client from the vendored spec.
fn gen() -> Result<()> {
    let raw = fs::read_to_string(SPEC_PATH)
        .with_context(|| format!("read {SPEC_PATH} (run `cargo xtask pull` first)"))?;
    let spec: openapiv3::OpenAPI = serde_json::from_str(&raw)?;

    let mut settings = GenerationSettings::default();
    settings
        .with_interface(InterfaceStyle::Builder)
        .with_tag(TagStyle::Separate)
        .with_inner_type(quote! { std::sync::Arc<crate::auth::TokenManager> })
        .with_pre_hook_async(quote! { crate::auth::inject_bearer })
        .with_post_hook_async(quote! { crate::auth::on_response })
        .with_derive("PartialEq");

    let tokens = Generator::new(&settings).generate_tokens(&spec)?;
    let ast = syn::parse2(tokens)?;
    let body = prettyplease::unparse(&ast);

    // Stamp the generated code with the spec revision it came from, and keep the sidecar in
    // sync with the spec we actually generated against.
    let prov = provenance(&raw)?;
    write_provenance(&prov)?;
    let header = format!(
        "\
// @generated by `cargo xtask gen` from openapi/utila.v2.json — DO NOT EDIT.
// spec: {} {} (openapi {}) · sha256:{} · source: {}
#![allow(clippy::all, clippy::pedantic, clippy::restriction, missing_docs, unused)]
",
        prov.title,
        prov.version,
        prov.openapi,
        short_sha(&prov.sha256),
        prov.source,
    );
    // The `// @generated` marker + `format_generated_files = false` in rustfmt.toml make
    // `cargo fmt` skip this file, so the prettyplease output is committed verbatim.
    fs::write(OUT_PATH, format!("{header}\n{body}"))?;
    eprintln!("wrote {OUT_PATH} ({} bytes)", body.len());
    Ok(())
}
